name: Check

on:
  pull_request: # Check Pull Requests

  push:
    branches:
      - master # Check branch after merge
jobs:
  runMain:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - run: ./mill app.runMain app.FooApp
